'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=c=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(c/100);
let csrf='',dirty=false,saveCurrent=null,tab='dashboard',busy=false;
function status(message){$('#admin-status').textContent=message}
async function api(path,data){
  const response=await fetch('/api/admin'+path,{method:data?'POST':'GET',headers:{Accept:'application/json',...(data?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(30000)});
  const result=await response.json();
  if(!response.ok){if(response.status===401){$('#login-form').hidden=false;status('Session expired. Sign in to continue; unsaved fields are retained.')}throw Error(result.error||'Request failed');}
  return result;
}
function track(){dirty=true;status('Unsaved changes')}
addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
async function canLeave(){
  if(!dirty)return true;
  const dialog=$('#unsaved-dialog');dialog.showModal();
  const choice=await new Promise(resolve=>{const click=e=>{if(!e.target.dataset.choice)return;dialog.removeEventListener('click',click);dialog.close();resolve(e.target.dataset.choice)};dialog.addEventListener('click',click);dialog.addEventListener('cancel',()=>{dialog.removeEventListener('click',click);resolve('stay')},{once:true})});
  if(choice==='stay')return false;
  if(choice==='save'){try{await saveCurrent();return !dirty}catch(e){status(e.message);return false}}
  dirty=false;return true;
}
document.addEventListener('click',async e=>{const a=e.target.closest('a[href]');if(a&&dirty){e.preventDefault();if(await canLeave())location.assign(a.href)}});
function field(label,name,value='',type='text',required=false){return `<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`}
function button(text,attrs=''){return `<button class="admin-button" ${attrs}>${esc(text)}</button>`}
function watch(form,save){dirty=false;saveCurrent=save;form.addEventListener('input',track);form.addEventListener('change',track);form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const buttons=form.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await save()}catch(e){status(e.message)}finally{busy=false;buttons.forEach(b=>b.disabled=false)}})}
function treeFields(value,path=[]){
  if(Array.isArray(value))return value.map((v,i)=>`<fieldset><legend>${esc(path.at(-1))} ${i+1}</legend>${treeFields(v,[...path,i])}</fieldset>`).join('');
  if(value&&typeof value==='object')return Object.entries(value).filter(([k])=>k!=='id').map(([k,v])=>`<div class="admin-field-group">${treeFields(v,[...path,k])}</div>`).join('');
  const name=esc(JSON.stringify(path)),label=esc(path.join(' / '));
  if(typeof value==='boolean')return `<label><input type="checkbox" data-path="${name}" ${value?'checked':''}> ${label}</label>`;
  if(typeof value==='number')return `<label>${label}<input type="number" step="any" data-path="${name}" value="${value}"></label>`;
  const image=/image|photo$/i.test(String(path.at(-1)))&&!/alt/i.test(String(path.at(-1)));
  return `<label>${label}<textarea data-path="${name}" rows="${String(value||'').length>140?4:2}">${esc(value??'')}</textarea></label>${image?`<label>Upload image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" data-upload-path="${name}"></label><img class="admin-preview" data-preview-path="${name}" alt="Image preview" ${value?`src="${esc(value)}"`:'hidden'}>`:''}`;
}
function collectTree(form,original){const value=structuredClone(original);form.querySelectorAll('[data-path]').forEach(input=>{const path=JSON.parse(input.dataset.path);let target=value;for(const k of path.slice(0,-1))target=target[k];target[path.at(-1)]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value});return value}
async function optimizeImage(file){
  if(!/^image\/(png|jpe?g|webp)$/i.test(file.type)||!('createImageBitmap'in window)||!HTMLCanvasElement.prototype.toBlob)return file;
  try{const bitmap=await createImageBitmap(file),scale=Math.min(1,1920/Math.max(bitmap.width,bitmap.height));if(scale===1&&file.type==='image/webp')return file;const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.84));return blob?new File([blob],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp'}):file;}catch{return file;}
}
function bindUploads(form){form.querySelectorAll('[data-upload-path]').forEach(input=>input.addEventListener('change',async()=>{const file=input.files[0];if(!file)return;if(file.size>25*1024*1024){status('Source image must be under 25 MB');return;}try{const optimized=await optimizeImage(file);if(optimized.size>5*1024*1024)throw Error('Optimized image must be under 5 MB');status(optimized!==file?'Image optimized for upload':'Uploading image');const section=input.dataset.uploadSection;const target=[...form.querySelectorAll('[data-path]')].find(e=>e.dataset.path===input.dataset.uploadPath&&(!section||e.dataset.contentSection===section));if(!target)throw Error('Image field is unavailable');const response=await fetch('/api/admin/upload',{method:'POST',headers:{'Content-Type':optimized.type,'X-CSRF-Token':csrf},body:optimized});const data=await response.json();if(!response.ok)throw Error(data.error);target.value=data.url;const preview=[...form.querySelectorAll('[data-preview-path]')].find(e=>e.dataset.previewPath===input.dataset.uploadPath&&(!section||e.dataset.previewSection===section));if(preview){preview.src=data.url;preview.hidden=false;}track();}catch(e){status(e.message)}}))}
function bindImageControls(form){
  form.querySelectorAll('[data-clear-image]').forEach(button=>button.addEventListener('click',()=>{const section=button.dataset.clearSection,path=button.dataset.clearImage;const target=[...form.querySelectorAll('[data-path]')].find(e=>e.dataset.path===path&&(!section||e.dataset.contentSection===section));const preview=[...form.querySelectorAll('[data-preview-path]')].find(e=>e.dataset.previewPath===path&&(!section||e.dataset.previewSection===section));const upload=[...form.querySelectorAll('[data-upload-path]')].find(e=>e.dataset.uploadPath===path&&(!section||e.dataset.uploadSection===section));if(target)target.value='';if(upload)upload.value='';if(preview){preview.hidden=true;preview.removeAttribute('src');}track();}));
  form.querySelectorAll('[data-preview-path]').forEach(preview=>{const section=preview.dataset.previewSection,path=preview.dataset.previewPath;const target=[...form.querySelectorAll('[data-path]')].find(e=>e.dataset.path===path&&(!section||e.dataset.contentSection===section));if(!target)return;target.addEventListener('input',()=>{const value=target.value.trim();if(value){preview.src=value;preview.hidden=false;}else{preview.hidden=true;preview.removeAttribute('src');}});});
}
async function loadTab(next){
  if(!(await canLeave()))return;
  tab=next;saveCurrent=null;status('Loading…');$('#admin-nav').querySelectorAll('button').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));
  try{await ({dashboard:dashboard,orders:orders,products:products,content:content,settings:settings}[tab])();status('Ready')}catch(e){status(e.message)}
}
async function dashboard(){
  const data=await api('/stats');
  $('#admin-view').innerHTML=`<h2>Dashboard</h2><div class="admin-fields">${Object.entries(data).filter(([,v])=>typeof v==='number').map(([k,v])=>`<p><strong>${v}</strong> ${esc(k)}</p>`).join('')}</div><h3>Services</h3><dl>${Object.entries(data.services).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v||'Not yet created')}</dd>`).join('')}</dl><h3>Recent orders</h3>${data.recentOrders.map(o=>`<p>${esc(o.id)} · ${money(o.total_cents)} · ${esc(o.payment_status)} / ${esc(o.shipping_status)} ${esc(o.issue)}</p>`).join('')||'<p>No orders yet.</p>'}<h3>Email queue</h3>${data.mail.map(m=>`<p>${esc(m.id)} · ${esc(m.recipient)} · ${esc(m.state)} ${m.state==='uncertain'?button('Review and retry',`type="button" data-retry="${esc(m.id)}"`):''}</p>`).join('')||'<p>No pending messages.</p>'}<h3>Activity</h3>${data.activity.map(a=>`<p>${esc(a.created_at)} · ${esc(a.action)} · ${esc(a.reference)}</p>`).join('')}<details><summary>Contact messages</summary><div id="messages"></div></details>`;
  $('#admin-view').querySelectorAll('[data-retry]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('The message may already have been delivered. Check the mailbox/provider first. Retry now?'))return;try{await api('/mail/retry',{id:b.dataset.retry,confirm:true});await dashboard()}catch(e){status(e.message)}}));
  const messages=await api('/messages');$('#messages').innerHTML=messages.messages.map(m=>`<article><h4>${esc(m.name)} · ${esc(m.email)}</h4><p class="preserve-lines">${esc(m.message)}</p></article>`).join('')||'No messages.';
}
async function orders(){
  const data=await api('/orders');
  $('#admin-view').innerHTML='<h2>Orders</h2><label>Search ID, email or name<input id="order-search" type="search"></label><label>Payment<select id="payment-filter"><option value="">All</option>'+['PENDING','PAID','FAILED','REFUNDED'].map(v=>`<option>${v}</option>`).join('')+'</select></label><label>Fulfillment<select id="fulfillment-filter"><option value="">All</option>'+['NEW','PREPARING','SHIPPED','DELIVERED'].map(v=>`<option>${v}</option>`).join('')+'</select></label><div id="order-list"></div>';
  function render(){const search=$('#order-search').value.toLowerCase(),payment=$('#payment-filter').value,fulfillment=$('#fulfillment-filter').value;
    $('#order-list').innerHTML=data.orders.filter(o=>(!payment||o.payment_status===payment)&&(!fulfillment||o.shipping_status===fulfillment)&&`${o.id} ${o.name} ${o.email}`.toLowerCase().includes(search)).map(o=>`<details class="admin-section"><summary>${esc(o.id)} · ${money(o.total_cents)} · ${esc(o.payment_status)} / ${esc(o.shipping_status)}</summary><p>${esc(o.name)} · ${esc(o.email)} · ${esc(o.phone)}</p><p>${esc([o.address,o.city,o.postcode,o.country].filter(Boolean).join(', '))}</p><p>Delivery: ${esc(o.shipping_method)} · ${money(o.shipping_cents)}</p><ul>${o.items.map(i=>`<li>${esc(i.sku)} · ${esc(i.name)} ${esc(i.variant)} · ${i.quantity} × ${money(i.priceCents)}</li>`).join('')}</ul><p>Stripe session: ${esc(o.stripe_session_id||'Not created')}</p><p>Payment reference: ${esc(o.payment_intent||'Pending')}</p>${o.issue?`<p role="alert">Attention: ${esc(o.issue)}</p>`:''}<form data-order="${esc(o.id)}"><label>Fulfillment<select name="fulfillmentStatus">${['NEW','PREPARING','SHIPPED','DELIVERED'].map(s=>`<option ${s===o.shipping_status?'selected':''}>${s}</option>`).join('')}</select></label>${field('Tracking reference / URL','tracking',o.tracking)}<label>Internal notes<textarea name="notes">${esc(o.notes)}</textarea></label>${button('Save fulfillment','type="submit" '+(o.payment_status!=='PAID'||o.issue?'disabled':''))}</form><p>Refunds: open this payment in Stripe, verify the amount and confirm the refund there. The signed refund webhook updates the payment state here. Stock is restored separately after checking the returned item.</p><a href="https://dashboard.stripe.com/payments" target="_blank" rel="noopener noreferrer">Open Stripe payments</a></details>`).join('')||'<p>No matching orders.</p>';
    $('#order-list').querySelectorAll('form').forEach(form=>{form.addEventListener('input',()=>{track();saveCurrent=()=>save(form)});form.addEventListener('change',()=>{track();saveCurrent=()=>save(form)});form.addEventListener('submit',async e=>{e.preventDefault();try{await save(form)}catch(e){status(e.message)}})});
  }
  async function save(form){await api('/orders/status',{orderId:form.dataset.order,...Object.fromEntries(new FormData(form))});dirty=false;status('Order saved');await orders()}
  for(const id of ['order-search','payment-filter','fulfillment-filter'])$('#'+id).addEventListener('change',async()=>{if(await canLeave())render()});render();
}
async function content(){
  const data=await api('/content'), pages={
    home:[['home',null,'Home content'],['images','home','Images']],
    live:[['pages','live','Page content'],['live',null,'Events'],['images','live','Images']],
    contact:[['pages','contact','Page content'],['contact',null,'Contact details'],['siteText','contact','Form labels'],['images','contact','Images']],
    shop:[['pages','shop','Page content'],['images','shop','Editorial images']],
    global:[['ticker',null,'Ticker'],['siteText',null,'Navigation and footer'],['matrix',null,'Matrix effect']]
  };
  const labels={eyebrow:'Eyebrow',titleLineOne:'Title line 1',titleLineTwo:'Title line 2',note:'Note',intro:'Intro',cta:'CTA',heroImage:'Primary image URL',heroAlt:'Primary image ALT text',signalText:'Signal strip text',signalStripLabel:'Signal strip label',introEyebrow:'Intro eyebrow',introTitleLineOne:'Intro title line 1',introTitleLineTwo:'Intro title line 2',introDescription:'Intro description',groupEyebrow:'Group eyebrow',groupTitleLineOne:'Group title line 1',groupTitleLineTwo:'Group title line 2',groupDescription:'Group description',groupSecondary:'Group secondary text',groupCta:'Group CTA',sectionNumber:'Section number',description:'Description',serviceTitleOne:'Service title line 1',serviceTitleTwo:'Service title line 2',formIntro:'Form intro',text:'Text',speed:'Speed',fontSize:'Font size',tagline:'Footer tagline',homeCta:'Home footer CTA',shopCta:'Shop footer CTA',liveCta:'Live footer CTA',contactCta:'Contact footer CTA',primary:'Primary image',secondary:'Secondary image',image:'Image URL',alt:'ALT text',motion:'Animation',name:'Name',date:'Date',isoDate:'ISO date',location:'Location',venue:'Venue',signal:'Signal',detail:'Detail',action:'Ticket label',ticketUrl:'Ticket URL',past:'Past event',visible:'Visible',home:'Home',shop:'Shop',live:'Live',contact:'Contact',bag:'Bag',cart:'Cart',skipToContent:'Skip link',liveUpdates:'Ticker label'};
  let page='home', originals={}, showcase=structuredClone(data.showcase||[]);
  const labelFor=k=>page==='shop'&&k==='note'?'Shop description':labels[k]||String(k).replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase());
  function fields(value,section,path=[]){
    if(Array.isArray(value))return value.map((item,index)=>`<fieldset><legend>${labelFor(path.at(-1)||'item')} ${index+1}</legend>${fields(item,section,[...path,index])}</fieldset>`).join('');
    if(value&&typeof value==='object')return Object.entries(value).filter(([key])=>key!=='id'&&!(section==='contact'&&path.length===0&&['email','instagram','instagramUrl','youtube','youtubeUrl'].includes(key))).map(([key,item])=>`<div class="admin-field-group">${typeof item==='object'&&item!==null?`<h4>${esc(labelFor(key))}</h4>`:''}${fields(item,section,[...path,key])}</div>`).join('');
    const encoded=esc(JSON.stringify(path)), name=path.at(-1), key=`${section}:${JSON.stringify(path)}`, image=/image$/i.test(name)&&name!=='alt';
    if(name==='motion')return `<label>${esc(labelFor(name))}<select data-content-section="${esc(section)}" data-path="${encoded}">${['none','zoom','drift','reveal'].map(mode=>`<option value="${mode}" ${value===mode?'selected':''}>${mode==='none'?'None':mode==='zoom'?'Slow zoom':mode[0].toUpperCase()+mode.slice(1)}</option>`).join('')}</select></label>`;
    if(typeof value==='boolean')return `<label><input type="checkbox" data-content-section="${esc(section)}" data-path="${encoded}" ${value?'checked':''}> ${esc(labelFor(name))}</label>`;
    const type=typeof value==='number'?'number':'text', large=typeof value==='string'&&(value.length>100||(page==='shop'&&name==='note')), numberAttrs=section==='matrix'&&name==='fontSize'?'min="8" max="32" step="1"':'step="any"';
    return `<label>${esc(section==='matrix'&&name==='fontSize'?'Matrix character size':labelFor(name))}${large?`<textarea data-content-section="${esc(section)}" data-path="${encoded}" rows="4">${esc(value??'')}</textarea>`:`<input type="${type}" ${type==='number'?numberAttrs:''} data-content-section="${esc(section)}" data-path="${encoded}" value="${esc(value??'')}">`}</label>${image?`<label>Upload optimized image<input type="file" accept="image/png,image/jpeg,image/webp" data-upload-section="${esc(section)}" data-upload-path="${encoded}"></label><img class="admin-preview" data-preview-section="${esc(section)}" data-preview-path="${encoded}" alt="Image preview" ${value?`src="${esc(value)}"`:''} ${value?'':'hidden'}><button class="admin-button secondary" type="button" data-clear-section="${esc(section)}" data-clear-image="${encoded}">Remove image</button>`:''}`;
  }
  function showcaseEditor(){return `<section class="admin-section"><h3>Shop showcase</h3><p>Catalogue content only. Prices, stock, shipping and checkout remain outside this V1 editor.</p><div class="showcase-items">${showcase.map((item,index)=>{const imagePath=esc(JSON.stringify(['shopShowcase',index,'image']));return `<fieldset data-showcase-item="${index}"><legend>Item ${index+1}</legend><label>Image URL<input data-path="${imagePath}" data-showcase-field="image" value="${esc(item.image||'')}"></label><label>Upload / replace image<input type="file" accept="image/png,image/jpeg,image/webp" data-upload-path="${imagePath}"></label><img class="admin-preview" data-preview-path="${imagePath}" alt="Current image preview" ${item.image?`src="${esc(item.image)}"`:''} ${item.image?'':'hidden'}><button class="admin-button secondary" type="button" data-clear-image="${imagePath}">Remove image</button><label>Product title<input data-showcase-field="title" maxlength="160" required value="${esc(item.title||'')}"></label><label>Product description<textarea data-showcase-field="description" rows="4" maxlength="5000">${esc(item.description||'')}</textarea></label><label>Image ALT text<input data-showcase-field="alt" maxlength="300" value="${esc(item.alt||'')}"></label><div class="admin-actions"><button class="admin-button secondary" type="button" data-showcase-action="up" ${index===0?'disabled':''}>Move up</button><button class="admin-button secondary" type="button" data-showcase-action="down" ${index===showcase.length-1?'disabled':''}>Move down</button><button class="admin-button secondary" type="button" data-showcase-action="remove">Remove item</button></div></fieldset>`}).join('')}</div><button class="admin-button secondary" type="button" id="showcase-add">Add item</button></section>`}
  function readShowcase(form){return [...form.querySelectorAll('[data-showcase-item]')].map((fieldset,index)=>({...(showcase[index]?.id?{id:showcase[index].id}:{}),image:fieldset.querySelector('[data-showcase-field="image"]').value.trim(),title:fieldset.querySelector('[data-showcase-field="title"]').value.trim(),description:fieldset.querySelector('[data-showcase-field="description"]').value,alt:fieldset.querySelector('[data-showcase-field="alt"]').value.trim()}))}
  function render(){
    originals=Object.fromEntries([...new Set(pages[page].map(([section])=>section))].map(section=>[section,structuredClone(data.content[section])]));
    $('#admin-view').innerHTML=`<h2>Content</h2><label>Page<select id="content-page">${[['home','Home'],['live','Live'],['contact','Contact'],['shop','Shop'],['global','Global / Site']].map(([key,name])=>`<option value="${key}">${name}</option>`).join('')}</select></label><form id="content-editor">${pages[page].map(([section,key,title])=>`<section class="admin-section"><h3>${esc(title)}</h3>${fields(key?originals[section][key]:originals[section],section,key?[key]:[])}</section>`).join('')}${page==='shop'?showcaseEditor():''}${button(page==='shop'?'Save Shop content':'Save page changes','type="submit"')}</form>`;
    $('#content-page').value=page;const form=$('#content-editor');
    watch(form,async()=>{const changed={};for(const section of Object.keys(originals))changed[section]=structuredClone(originals[section]);form.querySelectorAll('[data-content-section][data-path]').forEach(input=>{const section=input.dataset.contentSection,path=JSON.parse(input.dataset.path);let target=changed[section];for(const key of path.slice(0,-1))target=target[key];target[path.at(-1)]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;});for(const section of Object.keys(changed)){if(JSON.stringify(changed[section])===JSON.stringify(originals[section]))continue;const result=await api('/content',{section,value:changed[section],version:data.version});data.content=result.content;data.version=result.version;}if(page==='shop'){const result=await api('/showcase',{items:readShowcase(form)});data.showcase=result.items;showcase=structuredClone(result.items);}dirty=false;render();status(page==='shop'?'Shop showcase saved':'Page changes saved')});
    bindUploads(form);bindImageControls(form);
    if(page==='shop'){
      $('#showcase-add').addEventListener('click',()=>{showcase=readShowcase(form);showcase.push({image:'',title:'',description:'',alt:''});render();track();$('#content-editor [data-showcase-item]:last-of-type input[data-showcase-field="title"]')?.focus()});
      form.querySelectorAll('[data-showcase-action]').forEach(action=>action.addEventListener('click',()=>{showcase=readShowcase(form);const index=Number(action.closest('[data-showcase-item]').dataset.showcaseItem),kind=action.dataset.showcaseAction;if(kind==='remove')showcase.splice(index,1);if(kind==='up'&&index>0)[showcase[index-1],showcase[index]]=[showcase[index],showcase[index-1]];if(kind==='down'&&index<showcase.length-1)[showcase[index+1],showcase[index]]=[showcase[index],showcase[index+1]];render();track()}));
    }
    $('#content-page').addEventListener('change',async e=>{const next=e.target.value;if(await canLeave()){page=next;render()}else e.target.value=page});
  }
  render();
}async function products(){
  const data=await api('/products');let selected=null;
  $('#admin-view').innerHTML=`<h2>Products</h2><label>Product<select id="product-select"><option value="">New product</option>${data.products.map(p=>`<option value="${p.id}">${esc(p.sku)} · ${esc(p.name)}${p.active?'':' (hidden)'}</option>`).join('')}</select></label><div id="product-editor"></div><h3>Stock movements</h3><div>${data.history.map(h=>`<p>${esc(h.created_at)} · Product ${h.product_id}${h.variant_id?' / variant '+h.variant_id:''} · ${h.delta>0?'+':''}${h.delta} · ${esc(h.reason)} · ${esc(h.reference)}</p>`).join('')}</div>`;
  function render(p,isNew=!p?.id){selected=p;const original=p||{name:'',sku:'',meta:'',description:'',priceCents:0,image:'',alt:'',active:false,variants:[]};
    const editable={name:original.name,sku:original.sku,meta:original.meta||'',description:original.description||'',priceCents:original.priceCents,image:original.image||'',alt:original.alt||'',active:Boolean(original.active),variants:(original.variants||[]).map(v=>({...v,active:Boolean(v.active)}))};
    editable.variants=editable.variants.map(({id,sku,size,color,active})=>({...id?{id}:{},sku,size,color,active}));
    $('#product-editor').innerHTML=`<form id="product-form">${treeFields(editable)}<p>Prices are in cents. Stock is changed only in the separate form below.</p>${button('Add size / color variant','type="button" id="add-variant"')}${button('Save product details','type="submit"')}</form>${!isNew?`<form id="stock-form"><h3>Adjust stock</h3><label>Inventory<select name="variantId">${p.hasVariants?p.variants.map(v=>`<option value="${v.id}">${esc(v.sku)} — stock ${v.stock}, reserved ${v.reserved_stock}</option>`).join(''):`<option value="">${esc(p.sku)} — stock ${p.stock}, reserved ${p.reserved_stock}</option>`}</select></label>${field('Adjustment (e.g. 5 or -2)','delta',0,'number',true)}${field('Reason','reason','','text',true)}${button('Apply stock adjustment','type="submit"')}</form>`:''}`;
    const form=$('#product-form');watch(form,async()=>{const value=collectTree(form,editable);const result=await api('/products',{...value,...(!isNew?{id:p.id,version:p.version}:{})});dirty=false;status('Product saved');await products();$('#product-select').value=String(result.id);$('#product-select').dispatchEvent(new Event('change'))});bindUploads(form);
    $('#add-variant').addEventListener('click',()=>{const value=collectTree(form,editable);value.variants.push({sku:'',size:'',color:'',active:true});render({...original,...value},isNew);track()});
    const stock=$('#stock-form');if(stock)stock.addEventListener('submit',async e=>{e.preventDefault();if(dirty){status('Save product details before adjusting stock.');return;}const d=Object.fromEntries(new FormData(stock));if(!confirm(`Apply stock adjustment ${d.delta}?`))return;try{await api('/stock',{productId:p.id,variantId:d.variantId?Number(d.variantId):null,delta:Number(d.delta),reason:d.reason});await products();$('#product-select').value=String(p.id);$('#product-select').dispatchEvent(new Event('change'));status('Stock updated')}catch(e){status(e.message)}});
  }
  $('#product-select').addEventListener('change',async e=>{const id=e.target.value;if(await canLeave())render(data.products.find(p=>p.id===Number(id))||null);else e.target.value=selected?.id||''});render(null);
}
async function settings(){
  const data=await api('/settings');let draft=structuredClone(data.settings);
  function read(form){const base=collectTree(form,{domain:draft.domain,businessEmail:draft.businessEmail}),d=Object.fromEntries(new FormData(form));base.links=[...form.querySelectorAll('[data-social-item]')].map(row=>({label:row.querySelector('[data-social-field="label"]').value.trim(),url:row.querySelector('[data-social-field="url"]').value.trim()}));base.shipping={zones:d.zones.trim()?d.zones.trim().split('\n').map(line=>{const [name,countries,price]=line.split('|').map(v=>v.trim());if(!name||!countries||price==null||price==='')throw Error('Each zone needs name | countries | price in cents');return {name,countries:countries.toUpperCase().split(',').map(c=>c.trim()),priceCents:Number(price)}}):[],freeThresholdCents:d.freeThresholdCents===''?null:Number(d.freeThresholdCents),pickupEnabled:form.elements.pickupEnabled.checked,pickupAddress:d.pickupAddress,pickupInstructions:d.pickupInstructions};return base}
  function socialEditor(){return `<section class="admin-section"><h3>Social links</h3><p>One ordered source used by Contact and the public footer. Only complete HTTPS links are published.</p><div class="social-link-items">${draft.links.map((item,index)=>`<fieldset data-social-item="${index}"><legend>Social link ${index+1}</legend><label>Label<input data-social-field="label" maxlength="100" value="${esc(item.label)}"></label><label>HTTPS URL<input data-social-field="url" type="url" maxlength="2000" value="${esc(item.url)}"></label><div class="admin-actions"><button class="admin-button secondary" type="button" data-social-action="up" ${index===0?'disabled':''}>Move up</button><button class="admin-button secondary" type="button" data-social-action="down" ${index===draft.links.length-1?'disabled':''}>Move down</button><button class="admin-button secondary" type="button" data-social-action="remove">Remove link</button></div></fieldset>`).join('')}</div><button class="admin-button secondary" type="button" id="social-add">Add social link</button></section>`}
  function render(){
    $('#admin-view').innerHTML=`<h2>Settings</h2><form id="settings-form">${treeFields({domain:draft.domain,businessEmail:draft.businessEmail})}${socialEditor()}<h3>Shipping</h3><p>One zone per line: name | country codes separated by commas | price in cents.</p><label>Zones<textarea name="zones" rows="5">${esc(draft.shipping.zones.map(z=>`${z.name} | ${z.countries.join(',')} | ${z.priceCents}`).join('\n'))}</textarea></label>${field('Free shipping threshold in cents (empty = disabled)','freeThresholdCents',draft.shipping.freeThresholdCents??'','number')}<label><input name="pickupEnabled" type="checkbox" ${draft.shipping.pickupEnabled?'checked':''}> Enable local pickup</label>${field('Pickup address','pickupAddress',draft.shipping.pickupAddress)}<label>Pickup instructions<textarea name="pickupInstructions">${esc(draft.shipping.pickupInstructions)}</textarea></label><p>Pickup remains unavailable to customers until both address and instructions are filled.</p>${button('Save settings','type="submit"')}</form><h3>Backup</h3><p>Private backup includes a consistent SQLite snapshot and uploaded images.</p>${button('Create backup now','type="button" id="backup-now"')}<p id="backup-status" role="status"></p><p>Secrets are configured on the server, never in this panel.</p>`;
    const form=$('#settings-form');watch(form,async()=>{draft=read(form);await api('/settings',{value:draft,version:data.version});dirty=false;await settings();status('Settings saved')});
    $('#social-add').addEventListener('click',()=>{draft=read(form);draft.links.push({label:'',url:''});render();track();$('#settings-form [data-social-item]:last-of-type [data-social-field="label"]')?.focus()});
    form.querySelectorAll('[data-social-action]').forEach(action=>action.addEventListener('click',()=>{draft=read(form);const index=Number(action.closest('[data-social-item]').dataset.socialItem),kind=action.dataset.socialAction;if(kind==='remove')draft.links.splice(index,1);if(kind==='up'&&index>0)[draft.links[index-1],draft.links[index]]=[draft.links[index],draft.links[index-1]];if(kind==='down'&&index<draft.links.length-1)[draft.links[index+1],draft.links[index]]=[draft.links[index],draft.links[index+1]];render();track()}));
    $('#backup-now').addEventListener('click',async()=>{const b=$('#backup-now');b.disabled=true;try{const result=await api('/backup',{});$('#backup-status').textContent='Backup created: '+result.createdAt}catch(e){$('#backup-status').textContent=e.message}finally{b.disabled=false}});
  }
  render();
}
$('#admin-nav').addEventListener('click',e=>{if(e.target.dataset.tab)loadTab(e.target.dataset.tab)});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;try{const result=await api('/login',{password:new FormData(form).get('password')});csrf=result.csrfToken;form.reset();$('#login-form').hidden=true;$('#admin-app').hidden=false;$('#logout').hidden=false;if(!dirty)await loadTab(tab);else status('Signed in. Unsaved fields retained.')}catch(e){status(e.message)}});
$('#logout').addEventListener('click',async()=>{if(!(await canLeave()))return;try{await api('/logout',{});csrf='';$('#admin-app').hidden=true;$('#login-form').hidden=false;$('#logout').hidden=true;status('Signed out')}catch(e){status(e.message)}});
(async()=>{try{const data=await api('/session');csrf=data.csrfToken;$('#login-form').hidden=true;$('#admin-app').hidden=false;$('#logout').hidden=false;await loadTab('dashboard')}catch{status('Sign in to manage the site')}})();

